apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-processor
  labels:
    app: event-processor
spec:
  selector:
    matchLabels:
      app: event-processor
  template:
    metadata:
      labels:
        app: event-processor
    spec:
      containers:
      - name: event-processor
        image: yaronpr/sample-dotnet-eventhub-worker:latest
        env:
        - name: GLOBAL_AUTH_MODE
          value: "ConnectionString"
        - name: EVENTHUB_CONSUMERGROUP
          value: "$Default"
        - name: EVENTHUB_NAME
          value: "incming-test"
        - name: EVENTHUB_CONNECTIONSTRING
          valueFrom:
            secretKeyRef:
             name: secrets-event-consumer
             key: eventhub-connectionstring
        - name: BLOB_CHECKPOINT_CONTAINERNAME
          value: checkpointnew
        - name: BLOB_CHECKPOINT_CONNECTIONSTRING
          valueFrom:
            secretKeyRef:
              name: secrets-event-consumer
              key: blob-checkpoint-connectionstring
---
apiVersion: v1
kind: Secret
metadata:
  name: secrets-event-consumer
  labels:
    app: event-processor
data:
  eventhub-connectionstring: <BASE64 connection string>
  blob-checkpoint-connectionstring: <BASE64 connection string>
