apiVersion: keda.sh/v1alpha1 
kind: ScaledObject
metadata:
  name: event-processor-scaler
spec:
  scaleTargetRef:
    name: event-processor
  minReplicaCount: 0 # Change to define how many minimum replicas you want
  maxReplicaCount: 50 #the actual max replica is bounded by the event hub partitation which was configured
  pollingInterval:  10
  cooldownPeriod: 15
  triggers:
  - type: azure-eventhub
    metadata:
      connectionFromEnv: "EVENTHUB_FULL_CONNECTIONSTRING"
      storageConnectionFromEnv: "BLOB_CHECKPOINT_CONNECTIONSTRING"
      consumerGroup: "$Default"
      unprocessedEventThreshold: "64"
      blobContainer: "checkpointnew"
      checkpointStrategy: "blobMetadata"