apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-processor
  labels:
    app: event-processor
spec:
  selector:
    matchLabels:
      app: event-processor
  template:
    metadata:
      labels:
        app: event-processor
    spec:
      containers:
      - name: event-processor
        image: yaronpr/sample-dotnet-eventhub-worker:latest
        env:
        - name: GLOBAL_AUTH_MODE
          value: "ConnectionString"
        - name: EVENTHUB_CONSUMERGROUP
          value: "<REPLACE: CONSUMER GROUP NAME>"
        - name: EVENTHUB_NAME
          value: "<REPLACE: EVENTHUB NAME>"
        - name: EVENTHUB_CONNECTIONSTRING
          valueFrom:
            secretKeyRef:
             name: secrets-event-consumer
             key: eventhub-connectionstring
        - name: BLOB_CHECKPOINT_CONTAINERNAME
          value: "<REPLACE: BLOB CONTAINER NAME>"
        - name: BLOB_CHECKPOINT_CONNECTIONSTRING
          valueFrom:
            secretKeyRef:
              name: secrets-event-consumer
              key: blob-checkpoint-connectionstring
        - name: EVENTHUB_FULL_CONNECTIONSTRING
          valueFrom:
            secretKeyRef:
              name: secrets-event-consumer
              key: eventhub-checkpoint-full-connectionstring
---
apiVersion: v1
kind: Secret
metadata:
  name: secrets-event-consumer
  labels:
    app: event-processor
data:
  eventhub-connectionstring: <REPLACE BASE64 connection string>
  blob-checkpoint-connectionstring: <REPLACE BASE64 connection string>
  eventhub-checkpoint-full-connectionstring: <REPLACE BASE64 eventhub connection string with appended string ;EntityPath=EVENTHUB_NAME>